#!/bin/bash
# SPDX-FileCopyrightText: 2026 Adeveda Enterprises Private Limited
#
# SPDX-License-Identifier: GPL-2.0-or-later

set -euo pipefail

# MUNO Build Script
# Builds Blender (always Release) + MUNO (environment from settings.sh)

# Load all settings from settings.sh
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/settings.sh"

# Use MUNO_ENV directly from settings.sh (already exported there)
# Blender always builds in Release mode for optimal performance
BLENDER_BUILD_ENV="Release"

# Define build directory for this environment
BUILD_ENV_DIR="${BUILD_DIR}/${MUNO_ENV}"

# Overlay MUNO sources onto source
echo "Overlaying MUNO sources onto source..."
"$SCRIPT_DIR/overlay.sh"

# Configure build directory
mkdir -p "${BUILD_ENV_DIR}"

# Generate environment configuration header
echo "Generating environment configuration for: $MUNO_ENV"
mkdir -p "$SOURCE_DIR/source/creator"
cat > "$SOURCE_DIR/source/creator/muno_env_config.h" << EOF
#pragma once
// Auto-generated file - DO NOT EDIT
// Generated for environment: $MUNO_ENV

#define MUNO_BASE_URL "$MUNO_BACKEND_URL"
#define MUNO_FRONTEND_BASE_URL "$MUNO_FRONTEND_URL"
#define MUNO_CURRENT_ENV "$MUNO_ENV"

// Environment-specific macros for conditional compilation
EOF

# Generate environment-specific macro based on current MUNO_ENV
case "$MUNO_ENV" in
    "Prod")
        echo "#define MUNO_ENV_PROD" >> "$SOURCE_DIR/source/creator/muno_env_config.h"
        ;;
    "Dev")
        echo "#define MUNO_ENV_DEV" >> "$SOURCE_DIR/source/creator/muno_env_config.h"
        ;;
    "UAT"|"Uat")
        echo "#define MUNO_ENV_UAT" >> "$SOURCE_DIR/source/creator/muno_env_config.h"
        ;;
    *)
        echo "#define MUNO_ENV_PROD  // Default to production for unknown environment" >> "$SOURCE_DIR/source/creator/muno_env_config.h"
        ;;
esac

# Emit the build-frozen Python env marker (mirrors muno_env_config.h on the
# Python side). Used by muno.config.config.get_dev_bypass_credentials() to
# gate the dev bypass behind a value that cannot be flipped by editing the
# bundled muno.json. Only Dev builds get DEV_BYPASS_ALLOWED=True.
if [ "$MUNO_ENV" = "Dev" ]; then
    BUILD_ENV_DEV_BYPASS="True"
else
    BUILD_ENV_DEV_BYPASS="False"
fi
mkdir -p "$SOURCE_DIR/scripts/muno/config"
cat > "$SOURCE_DIR/scripts/muno/config/_build_env.py" << EOF
# SPDX-FileCopyrightText: 2026 Adeveda Enterprises Private Limited
# SPDX-License-Identifier: GPL-2.0-or-later
# Auto-generated by scripts/unix/build.sh - DO NOT EDIT
BUILD_ENVIRONMENT = "$MUNO_ENV"
DEV_BYPASS_ALLOWED = $BUILD_ENV_DEV_BYPASS
EOF

# Configure with CMake (all platform logic handled in settings.sh)
echo "Configuring MUNO build - Blender: $BLENDER_BUILD_ENV, MUNO Environment: $MUNO_ENV for $PLATFORM..."
cmake -C "$CMAKE_DIR/muno_overrides.cmake" \
    $CMAKE_GENERATOR_ARGS \
    -S "$SOURCE_DIR" \
    -B "$BUILD_ENV_DIR" \
    -DCMAKE_BUILD_TYPE="$BLENDER_BUILD_ENV" \
    -DMUNO_ENABLE_CUDA="$MUNO_ENABLE_CUDA" \
    -DMUNO_ENABLE_OPTIX="$MUNO_ENABLE_OPTIX" \
    -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

# Build (all platform-specific args handled in settings.sh)
echo "Building Blender in $BLENDER_BUILD_ENV mode for MUNO environment: $MUNO_ENV"
echo "Using $BUILD_CORES cores for parallel build"
cmake --build "$BUILD_ENV_DIR" --config "$BLENDER_BUILD_ENV" --parallel "$BUILD_CORES"
cmake --build "$BUILD_ENV_DIR" --target install --config "$BLENDER_BUILD_ENV" --parallel "$BUILD_CORES"

# Install Python packages using the generated Python binary
echo "Installing Python packages for MUNO..."

# Determine base path for embedded Python based on platform
if [[ "$PLATFORM" == "macOS" ]]; then
    PY_BASE=""
    for app_bundle in \
        "$BUILD_ENV_DIR/bin/MUNO.app" \
        "$BUILD_ENV_DIR/bin/Blender.app"; do
        if [[ -d "$app_bundle/Contents/Resources" ]]; then
            PY_BASE="$app_bundle/Contents/Resources"
            break
        fi
    done
    if [[ -z "$PY_BASE" ]]; then
        echo "Error: no MUNO.app or Blender.app bundle found under $BUILD_ENV_DIR/bin" >&2
        exit 1
    fi
elif [[ "$PLATFORM" == "Linux" ]]; then
    PY_BASE="$BUILD_ENV_DIR/bin"
else
    echo "Error: Unsupported platform: $PLATFORM"
    exit 1
fi

# Do not assume the resource directory exactly matches BLENDER_VERSION. This
# also keeps packaging working across Blender patch/minor version updates.
RESOURCE_VERSION="$BLENDER_VERSION"
if [[ ! -d "$PY_BASE/$RESOURCE_VERSION/python" ]]; then
    RESOURCE_VERSION=""
    for version_dir in "$PY_BASE"/*; do
        if [[ -d "$version_dir/python/bin" ]]; then
            RESOURCE_VERSION="$(basename "$version_dir")"
            break
        fi
    done
fi
if [[ -z "$RESOURCE_VERSION" ]]; then
    echo "Error: embedded Python resources not found under $PY_BASE" >&2
    exit 1
fi

# Generate runtime configuration in the platform-correct resource tree.
echo "Generating runtime configuration for bundle..."
BUNDLE_CONFIG_DIR="$PY_BASE/$RESOURCE_VERSION/config"
python3 "$ROOT_DIR/scripts/generate_config.py" --output "$BUNDLE_CONFIG_DIR/muno.json"

# Try common python binary names inside Blender's embedded Python
PYTHON_BIN=""
for candidate in \
    "$PY_BASE/$RESOURCE_VERSION/python/bin/python${PYTHON_VERSION}" \
    "$PY_BASE/$RESOURCE_VERSION/python/bin/python3" \
    "$PY_BASE/$RESOURCE_VERSION/python/bin/python"; do
    if [[ -x "$candidate" ]]; then
        PYTHON_BIN="$candidate"
        break
    fi
done

SITE_PACKAGES=""
for site_dir in "$PY_BASE/$RESOURCE_VERSION/python/lib"/python*/site-packages; do
    if [[ -d "$site_dir" ]]; then
        SITE_PACKAGES="$site_dir"
        break
    fi
done
if [[ -z "$SITE_PACKAGES" ]]; then
    SITE_PACKAGES="$PY_BASE/$RESOURCE_VERSION/python/lib/python${PYTHON_VERSION}/site-packages"
fi
REQUIREMENTS_FILE="$(dirname "$SCRIPT_DIR")/python_requirements.txt"

if [[ -n "$PYTHON_BIN" ]]; then
    echo "Found Python binary: $PYTHON_BIN"
    mkdir -p "$SITE_PACKAGES"

    # Check if requirements file exists
    if [[ -f "$REQUIREMENTS_FILE" ]]; then
        echo "Installing packages from: $REQUIREMENTS_FILE"

        # Force pip to install to the embedded Python's site-packages
        # Use --no-user to prevent installation to user site-packages
        # Use --target to specify the exact location
        if "$PYTHON_BIN" -m pip install --no-user --target "$SITE_PACKAGES" -r "$REQUIREMENTS_FILE"; then
            echo "Successfully installed Python packages to embedded Python site-packages"
        elif command -v pip3 >/dev/null 2>&1; then
            echo "Embedded pip failed, trying system pip with --target..."
            if pip3 install --target "$SITE_PACKAGES" -r "$REQUIREMENTS_FILE"; then
                echo "Successfully installed Python packages using system pip"
            else
                echo "Warning: Failed to install Python packages from requirements file"
            fi
        else
            echo "Warning: No pip available, skipping Python package installation"
        fi
    else
        echo "Warning: Requirements file not found at: $REQUIREMENTS_FILE"
        exit 1
    fi
else
    echo "Error: Python binary not found under: $PY_BASE/$RESOURCE_VERSION/python/bin" >&2
    exit 1
fi

# Done
echo "=== Build Complete ==="
echo "Python packages installed from: $REQUIREMENTS_FILE"
echo "Run MUNO using: $ROOT_DIR/scripts/unix/run.sh $MUNO_ENV"
